---

collections:
  - name: awx.awx
    version: '>=22.7.0'
  - name: ansible.controller
    version: '>=4.0.0'
  - name: infra.controller_configuration
    version: '>=2.5.0'
  - name: infra.ah_configuration
    version: '>=1.1.1'

...