---

controller_credential_types: 

  - name: Generic API Credential
    description: Generic API Credential
    inputs:
      fields:
      - type: string
        id: api_hostname
        label: API Host
      - type: string
        id: api_username
        label: API Username
      - type: string
        id: api_password
        label: API Password
        secret: true
      - type: boolean
        id: api_ssl_verify
        label: Verify SSL 
      - type: string
        id: api_token
        label: API Token
        secret: true
      required:
      - api_username
      - api_password
    injectors:
      extra_vars:
        api_hostname: !unsafe '{{ api_hostname }}'
        api_username: !unsafe '{{ api_username }}'
        api_password: !unsafe '{{ api_password }}'
        api_token: !unsafe '{{ api_token }}'
        api_ssl_verify: !unsafe '{{ api_ssl_verify }}'
      env:
        API_HOSTNAME: !unsafe '{{ api_hostname }}'
        API_USERNAME: !unsafe '{{ api_username }}'
        API_PASSWORD: !unsafe '{{ api_password }}'
        API_TOKEN: !unsafe '{{ api_token }}'
        API_SSL_VERIFY: !unsafe '{{ api_ssl_verify }}'

  - name: Red Hat SSO Credential
    description: Credentials to access Red Hat related websites
    inputs:
      fields:
        - id: redhat_sso_username
          label: Username
          type: string
        - id: redhat_sso_password
          label: Password
          type: string
          secret: true
      required:
        - redhat_sso_username
        - redhat_sso_password
    injectors:
      extra_vars:
        redhat_sso_username: !unsafe '{{ redhat_sso_username }}'
        redhat_sso_password: !unsafe '{{ redhat_sso_password }}'
      env:
        REDHAT_SSO_USERNAME: !unsafe '{{ redhat_sso_username }}'
        REDHAT_SSO_PASSWORD: !unsafe '{{ redhat_sso_password }}'

...
