---

controller_settings:
  settings: 
    MAX_FORKS: "{{ controller_setting_max_forks | default('100') }}"
    GALAXY_IGNORE_CERTS: "{{ controller_setting_galaxy_ignore_certs | default('false') }}"
    AWX_COLLECTIONS_ENABLED: "{{ controller_setting_awx_collections_enabled | default('false') }}"
    AWX_ANSIBLE_CALLBACK_PLUGINS: "{{ awx_ansible_callback_plugins }}"
    AUTH_LDAP_SERVER_URI: "{{ auth_ldap_server_uri | default(omit)}}"
    AUTH_LDAP_BIND_DN: "{{ auth_ldap_bind_dn | default(omit) }}"
    AUTH_LDAP_BIND_PASSWORD: "{{ auth_ldap_bind_password | default(omit) }}"
    AUTH_LDAP_START_TLS: "{{ auth_ldap_start_tls | default(false) }}"
    AUTH_LDAP_USER_SEARCH: 
      - "{{ auth_ldap_base_dn }}"
      - "SCOPE_SUBTREE"
      - "(sAMAccountName=%(user)s)"
    AUTH_LDAP_USER_DN_TEMPLATE: ''
    AUTH_LDAP_USER_ATTR_MAP: 
      first_name: givenName
      last_name: sn
      email: mail
    AUTH_LDAP_GROUP_SEARCH:
      - "{{ auth_ldap_base_dn }}"
      - SCOPE_SUBTREE
      - (objectClass=group)
    AUTH_LDAP_GROUP_TYPE: "{{ auth_ldap_group_type }}"
    AUTH_LDAP_GROUP_TYPE_PARAMS: 
      name_attr: cn
    AUTH_LDAP_CONNECTION_OPTIONS: 
      OPT_REFERRALS: 0
    AUTH_LDAP_REQUIRE_GROUP: ''
    AUTH_LDAP_DENY_GROUP: ''
    AUTH_LDAP_USER_FLAGS_BY_GROUP: {}
    AUTH_LDAP_ORGANIZATION_MAP: "{{ auth_ldap_org_map }}"
    AUTH_LDAP_TEAM_MAP: "{{ auth_ldap_team_map }}"

...
