---

controller_credentials:

  - name: AAP Controller Credentials
    description: Controller Credentials
    credential_type: Red Hat Ansible Automation Platform
    organization: "{{ controller_as_code_org }}"
    inputs:  
      host: "{{ controller_hostname }}"
      username: "{{ controller_username }}"
      password: "{{ controller_password }}"

  - name: Controller as Code Repository Credentials
    description: Repo credentials where the CaC is stored
    credential_type: Source Control
    organization: "{{ controller_as_code_org }}"
    inputs:
      username: "{{ git_repo_usernam }}"
      ssh_key_data: "{{ git_repo_private_key | trim }}"

  - name: PAH Container Registry
    description: Private Automation Hub Container Registry
    credential_type: Container Registry
    organization: "{{ controller_as_code_org }}"
    inputs:
      host: "{{ pah_host_url }}"
      username: "{{ pah_username }}"
      password: "{{ pah_password }}"
      verify_ssl: false

  - name: PAH RH Certified
    description: Private Automation Hub RH Certified Repository
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: "{{ controller_as_code_org }}"
    inputs:
      url: "{{ pah_rh_certified_url }}"
      token: "{{ pah_token }}"

  - name: PAH RH Community
    description: Private Automation Hub Community Repository
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: "{{ controller_as_code_org }}"
    inputs:
      url: "{{ pah_rh_community_url }}"
      token: "{{ pah_token }}"

  - name: PAH RH Validated
    description: Private Automation Hub RH Validated Repository
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: "{{ controller_as_code_org }}"
    inputs:
      url: "{{ pah_rh_validated_url }}"
      token: "{{ pah_token }}"

  - name: Red Hat Automation Hub
    description: Red Hat Automation Hub 
    credential_type: Generic API Credential
    organization: "{{ controller_as_code_org }}"
    inputs: 
      api_hostname: "{{ redhat_sso_url }}"
      api_username: "{{ redhat_sso_username }}"
      api_password: "{{ redhat_sso_password }}"
      api_token: "{{ redhat_sso_token }}"

...
