---
- name: Deploy Ansible Automation Platform Controller as Code
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:

    - name: Deploy controller core settings
      ansible.builtin.include_role:
        name: deploy_aap2_controller_configurations

...
